services:
  obsidian-mcp:
    image: mcp/obsidian:latest
    container_name: obsidian-mcp
    restart: unless-stopped
    stdin_open: true
    tty: false
    environment:
      OBSIDIAN_HOST: "host.docker.internal"
      OBSIDIAN_API_KEY: "${OBSIDIAN_API_KEY}"
    env_file:
      - ./.env
    volumes:
      - ./vault:/vault

  youtube_transcript:
    image: mcp/youtube-transcript
    container_name: youtube_transcript
    stdin_open: true      # same as -i
    tty: true
    restart: "no"
