# -------------- APP Config --------------
APP_NAME: "ObsidianMate"
APP_VERSION: "1.0.0"

# -------------- Path Config --------------
PATH_LOGS: "logs"
PATH_DATA_ROOT: "data"
PATH_ASSETS_ROOT: "assets"
PATH_MODELS_ROOT: "models"
PATH_OUTPUT_ROOT: "output"

# -------------- Retry Config --------------
RETRY_ATTEMPS: 5
RETRY_EXP_BASE: 7  
RETRY_INITAL_RETRY: 1
RETRY_HTTP_STATUS_CODE: [429, 500, 503, 504]

# -------------- Model Config --------------
CHATT_MODEL_NAME: "gemini-2.5-flash-lite"
CLEAN_MODEL_NAME: "gemini-2.5-flash-lite"
SUMMARIZE_MODEL_NAME: "gemini-2.5-flash-lite"
MARKDOWN_MODEL_NAME: "gemini-2.5-flash-lite"
DIAGRAM_MODEL_NAME: "gemini-2.5-flash-lite"
WRITE_MODEL_NAME: "gemini-2.5-flash-lite"
